version: '2'
services:
  site_a:
    image: nginx:1.13.0-alpine
    container_name: site_a
    ports:
      - "8080:80"
    volumes:
      - ./site_a:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  site_b:
    image: nginx:1.13.0-alpine
    container_name: site_b
    ports:
      - "8081:80"
    volumes:
      - ./site_b:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  docker_proxy:
    image: nginx
    container_name: docker_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
